#ifndef H_LAYOUTS
#define H_LAYOUTS
#include "keyboard_functional.h"

const Keycode DEFAULT_LAYER[4][12] = {
    {KEY_TAB,           KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I,     KEY_O,      KEY_P,         KEY_BACKSPACE},
    {KEY_ESC,           KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K,     KEY_L,      KEY_SEMICOLON, KEY_ENTER},
    {MODIFIERKEY_SHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SLASH,     MODIFIERKEY_RIGHT_SHIFT},

    {MODIFIERKEY_CTRL,  MODIFIERKEY_ALT, MODIFIERKEY_GUI, MODIFIERKEY_SHIFT, Z::FN_LOWER, KEY_SPACE, KEY_BACKSPACE, Z::FN_RAISE, MODIFIERKEY_RIGHT_ALT, 0x0F, 0x0F, 0x0F}
};

#endif
